on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  main:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        node-version: [18, 16]
        dep-ver-webpack: ['^5', '5.61.0']
    runs-on: ${{ matrix.os }}
    env:
      E2E_DEP_VER_WEBPACK: ${{ matrix.dep-ver-webpack }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build
      - run: node scripts/e2e-with-debuglog.js
