on:
  push:
    branches:
      - master
      - beta
      - latest

jobs:
  lint-code:
    uses: ./.github/workflows/lint-code.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  release:
    needs:
      - lint-code
      - e2e
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run build
      - env:
          NPM_TOKEN: ${{secrets.SL_NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.SL_GITHUB_TOKEN}}
        run: npx -y semantic-release@19
